// GENERATED — do not hand-edit the map body.
// Every `mdi-*` token under frontend/src plus every Vuetify alias target
// (dropdown chevrons, checkboxes, sort arrows), resolved to its Material Design
// Icons path. `tests/mdiIconCoverage.spec.ts` re-derives the same inventory and
// fails when a reference has no entry here, so adding an icon to a template
// without regenerating breaks tests instead of silently rendering a blank box.
//
// Only these paths are pulled out of @mdi/js, so the bundle carries the 209
// icons this app renders instead of the full 7,447-glyph webfont.
import {
	mdiAccount,
	mdiAccountCashOutline,
	mdiAccountCircleOutline,
	mdiAccountEdit,
	mdiAccountGroupOutline,
	mdiAccountHeartOutline,
	mdiAccountOutline,
	mdiAccountSwitchOutline,
	mdiAlert,
	mdiAlertCircle,
	mdiAlertCircleOutline,
	mdiAlertOctagon,
	mdiAppleKeyboardCommand,
	mdiAppleKeyboardControl,
	mdiAppleKeyboardOption,
	mdiAppleKeyboardShift,
	mdiApplicationOutline,
	mdiArrowDown,
	mdiArrowLeft,
	mdiArrowRight,
	mdiArrowUp,
	mdiArrowUpBold,
	mdiBackspace,
	mdiBackupRestore,
	mdiBarcode,
	mdiBarcodeScan,
	mdiBellAlertOutline,
	mdiBellOffOutline,
	mdiBellOutline,
	mdiBookSearch,
	mdiBroom,
	mdiCached,
	mdiCalculator,
	mdiCalendar,
	mdiCalendarCheck,
	mdiCalendarClock,
	mdiCalendarMonthOutline,
	mdiCamera,
	mdiCameraOff,
	mdiCameraSwitch,
	mdiCardAccountDetailsOutline,
	mdiCartArrowDown,
	mdiCartOutline,
	mdiCartPlus,
	mdiCashCheck,
	mdiCashMinus,
	mdiCashMultiple,
	mdiCashPlus,
	mdiCashRefund,
	mdiCashRegister,
	mdiCashSync,
	mdiCellphoneArrowDown,
	mdiChartBar,
	mdiChartDonut,
	mdiCheck,
	mdiCheckBold,
	mdiCheckCircle,
	mdiCheckCircleOutline,
	mdiCheckboxBlankOutline,
	mdiCheckboxMarked,
	mdiChevronDown,
	mdiChevronLeft,
	mdiChevronRight,
	mdiChevronUp,
	mdiChip,
	mdiCircle,
	mdiCircleOutline,
	mdiClockOutline,
	mdiClose,
	mdiCloseCircle,
	mdiCloseCircleOutline,
	mdiCloudSyncOutline,
	mdiCloudUpload,
	mdiCogOutline,
	mdiConnection,
	mdiContactlessPayment,
	mdiContentSave,
	mdiContentSaveMoveOutline,
	mdiCounter,
	mdiCreditCard,
	mdiCreditCardMultiple,
	mdiCreditCardOutline,
	mdiCreditCardWireless,
	mdiCreditCardWirelessOutline,
	mdiCurrencyUsd,
	mdiDatabase,
	mdiDatabaseClock,
	mdiDatabaseOutline,
	mdiDatabaseSettings,
	mdiDelete,
	mdiDeleteOutline,
	mdiDomain,
	mdiDotsVertical,
	mdiDownload,
	mdiEyeOffOutline,
	mdiEyeOutline,
	mdiEyePlus,
	mdiEyedropper,
	mdiFileClockOutline,
	mdiFileDocumentMultipleOutline,
	mdiFileDocumentOutline,
	mdiFilePdfBox,
	mdiFileSearchOutline,
	mdiFinance,
	mdiFlashOutline,
	mdiFlashlight,
	mdiFlashlightOff,
	mdiFolder,
	mdiFolderOpenOutline,
	mdiFolderOutline,
	mdiFolderSearchOutline,
	mdiFormTextboxPassword,
	mdiFormatListBulleted,
	mdiFormatListNumbered,
	mdiFullscreen,
	mdiFullscreenExit,
	mdiHeart,
	mdiHelpCircle,
	mdiImage,
	mdiInformation,
	mdiInformationOutline,
	mdiKeyboardReturn,
	mdiKeyboardSpace,
	mdiLightbulbOnOutline,
	mdiLockOpenOutline,
	mdiLockOutline,
	mdiLogout,
	mdiMagnify,
	mdiMemory,
	mdiMenu,
	mdiMenuDown,
	mdiMenuRight,
	mdiMinus,
	mdiMinusBox,
	mdiMonitor,
	mdiMonitorDashboard,
	mdiMonitorEye,
	mdiMoonWaningCrescent,
	mdiNetworkPos,
	mdiNumeric,
	mdiOpenInNew,
	mdiPackageVariant,
	mdiPackageVariantClosed,
	mdiPageFirst,
	mdiPageLast,
	mdiPalette,
	mdiPaperclip,
	mdiPause,
	mdiPencil,
	mdiPencilOutline,
	mdiPercent,
	mdiPlay,
	mdiPlus,
	mdiPointOfSale,
	mdiPrinter,
	mdiPrinterCheck,
	mdiPrinterOutline,
	mdiPrinterPos,
	mdiPrinterSettings,
	mdiPrinterWireless,
	mdiProgressClock,
	mdiRadioboxBlank,
	mdiRadioboxMarked,
	mdiReceiptTextClockOutline,
	mdiReceiptTextOutline,
	mdiRefresh,
	mdiRefreshCircle,
	mdiReload,
	mdiSafe,
	mdiScaleBalance,
	mdiServer,
	mdiSourceBranch,
	mdiSourceCommit,
	mdiStar,
	mdiStarHalfFull,
	mdiStarOutline,
	mdiStoreClockOutline,
	mdiStorefrontOutline,
	mdiSync,
	mdiTable,
	mdiTagMinus,
	mdiTagOutline,
	mdiTextBoxCheckOutline,
	mdiTextBoxOutline,
	mdiThemeLightDark,
	mdiTicketPercentOutline,
	mdiTimerOutline,
	mdiTimerSand,
	mdiTranslate,
	mdiTrayFull,
	mdiTruckDeliveryOutline,
	mdiTune,
	mdiTuneVertical,
	mdiUndo,
	mdiUndoVariant,
	mdiUnfoldMoreHorizontal,
	mdiUpdate,
	mdiViewDashboardOutline,
	mdiViewGridOutline,
	mdiVolumeHigh,
	mdiVolumeLow,
	mdiVolumeMedium,
	mdiVolumeVariantOff,
	mdiWalletGiftcard,
	mdiWarehouse,
	mdiWeight,
	mdiWeightPound,
	mdiWhiteBalanceSunny,
	mdiWifi,
	mdiWifiOff,
	mdiWifiStrengthAlertOutline,
	mdiWifiSync,
	mdiWrenchCheckOutline,
	mdiWrenchOutline,
} from "@mdi/js";

export const mdiIconPaths: Record<string, string> = {
	"mdi-account": mdiAccount,
	"mdi-account-cash-outline": mdiAccountCashOutline,
	"mdi-account-circle-outline": mdiAccountCircleOutline,
	"mdi-account-edit": mdiAccountEdit,
	"mdi-account-group-outline": mdiAccountGroupOutline,
	"mdi-account-heart-outline": mdiAccountHeartOutline,
	"mdi-account-outline": mdiAccountOutline,
	"mdi-account-switch-outline": mdiAccountSwitchOutline,
	"mdi-alert": mdiAlert,
	"mdi-alert-circle": mdiAlertCircle,
	"mdi-alert-circle-outline": mdiAlertCircleOutline,
	"mdi-alert-octagon": mdiAlertOctagon,
	"mdi-apple-keyboard-command": mdiAppleKeyboardCommand,
	"mdi-apple-keyboard-control": mdiAppleKeyboardControl,
	"mdi-apple-keyboard-option": mdiAppleKeyboardOption,
	"mdi-apple-keyboard-shift": mdiAppleKeyboardShift,
	"mdi-application-outline": mdiApplicationOutline,
	"mdi-arrow-down": mdiArrowDown,
	"mdi-arrow-left": mdiArrowLeft,
	"mdi-arrow-right": mdiArrowRight,
	"mdi-arrow-up": mdiArrowUp,
	"mdi-arrow-up-bold": mdiArrowUpBold,
	"mdi-backspace": mdiBackspace,
	"mdi-backup-restore": mdiBackupRestore,
	"mdi-barcode": mdiBarcode,
	"mdi-barcode-scan": mdiBarcodeScan,
	"mdi-bell-alert-outline": mdiBellAlertOutline,
	"mdi-bell-off-outline": mdiBellOffOutline,
	"mdi-bell-outline": mdiBellOutline,
	"mdi-book-search": mdiBookSearch,
	"mdi-broom": mdiBroom,
	"mdi-cached": mdiCached,
	"mdi-calculator": mdiCalculator,
	"mdi-calendar": mdiCalendar,
	"mdi-calendar-check": mdiCalendarCheck,
	"mdi-calendar-clock": mdiCalendarClock,
	"mdi-calendar-month-outline": mdiCalendarMonthOutline,
	"mdi-camera": mdiCamera,
	"mdi-camera-off": mdiCameraOff,
	"mdi-camera-switch": mdiCameraSwitch,
	"mdi-card-account-details-outline": mdiCardAccountDetailsOutline,
	"mdi-cart-arrow-down": mdiCartArrowDown,
	"mdi-cart-outline": mdiCartOutline,
	"mdi-cart-plus": mdiCartPlus,
	"mdi-cash-check": mdiCashCheck,
	"mdi-cash-minus": mdiCashMinus,
	"mdi-cash-multiple": mdiCashMultiple,
	"mdi-cash-plus": mdiCashPlus,
	"mdi-cash-refund": mdiCashRefund,
	"mdi-cash-register": mdiCashRegister,
	"mdi-cash-sync": mdiCashSync,
	"mdi-cellphone-arrow-down": mdiCellphoneArrowDown,
	"mdi-chart-bar": mdiChartBar,
	"mdi-chart-donut": mdiChartDonut,
	"mdi-check": mdiCheck,
	"mdi-check-bold": mdiCheckBold,
	"mdi-check-circle": mdiCheckCircle,
	"mdi-check-circle-outline": mdiCheckCircleOutline,
	"mdi-checkbox-blank-outline": mdiCheckboxBlankOutline,
	"mdi-checkbox-marked": mdiCheckboxMarked,
	"mdi-chevron-down": mdiChevronDown,
	"mdi-chevron-left": mdiChevronLeft,
	"mdi-chevron-right": mdiChevronRight,
	"mdi-chevron-up": mdiChevronUp,
	"mdi-chip": mdiChip,
	"mdi-circle": mdiCircle,
	"mdi-circle-outline": mdiCircleOutline,
	"mdi-clock-outline": mdiClockOutline,
	"mdi-close": mdiClose,
	"mdi-close-circle": mdiCloseCircle,
	"mdi-close-circle-outline": mdiCloseCircleOutline,
	"mdi-cloud-sync-outline": mdiCloudSyncOutline,
	"mdi-cloud-upload": mdiCloudUpload,
	"mdi-cog-outline": mdiCogOutline,
	"mdi-connection": mdiConnection,
	"mdi-contactless-payment": mdiContactlessPayment,
	"mdi-content-save": mdiContentSave,
	"mdi-content-save-move-outline": mdiContentSaveMoveOutline,
	"mdi-counter": mdiCounter,
	"mdi-credit-card": mdiCreditCard,
	"mdi-credit-card-multiple": mdiCreditCardMultiple,
	"mdi-credit-card-outline": mdiCreditCardOutline,
	"mdi-credit-card-wireless": mdiCreditCardWireless,
	"mdi-credit-card-wireless-outline": mdiCreditCardWirelessOutline,
	"mdi-currency-usd": mdiCurrencyUsd,
	"mdi-database": mdiDatabase,
	"mdi-database-clock": mdiDatabaseClock,
	"mdi-database-outline": mdiDatabaseOutline,
	"mdi-database-settings": mdiDatabaseSettings,
	"mdi-delete": mdiDelete,
	"mdi-delete-outline": mdiDeleteOutline,
	"mdi-domain": mdiDomain,
	"mdi-dots-vertical": mdiDotsVertical,
	"mdi-download": mdiDownload,
	"mdi-eye-off-outline": mdiEyeOffOutline,
	"mdi-eye-outline": mdiEyeOutline,
	"mdi-eye-plus": mdiEyePlus,
	"mdi-eyedropper": mdiEyedropper,
	"mdi-file-clock-outline": mdiFileClockOutline,
	"mdi-file-document-multiple-outline": mdiFileDocumentMultipleOutline,
	"mdi-file-document-outline": mdiFileDocumentOutline,
	"mdi-file-pdf-box": mdiFilePdfBox,
	"mdi-file-search-outline": mdiFileSearchOutline,
	"mdi-finance": mdiFinance,
	"mdi-flash-outline": mdiFlashOutline,
	"mdi-flashlight": mdiFlashlight,
	"mdi-flashlight-off": mdiFlashlightOff,
	"mdi-folder": mdiFolder,
	"mdi-folder-open-outline": mdiFolderOpenOutline,
	"mdi-folder-outline": mdiFolderOutline,
	"mdi-folder-search-outline": mdiFolderSearchOutline,
	"mdi-form-textbox-password": mdiFormTextboxPassword,
	"mdi-format-list-bulleted": mdiFormatListBulleted,
	"mdi-format-list-numbered": mdiFormatListNumbered,
	"mdi-fullscreen": mdiFullscreen,
	"mdi-fullscreen-exit": mdiFullscreenExit,
	"mdi-heart": mdiHeart,
	"mdi-help-circle": mdiHelpCircle,
	"mdi-image": mdiImage,
	"mdi-information": mdiInformation,
	"mdi-information-outline": mdiInformationOutline,
	"mdi-keyboard-return": mdiKeyboardReturn,
	"mdi-keyboard-space": mdiKeyboardSpace,
	"mdi-lightbulb-on-outline": mdiLightbulbOnOutline,
	"mdi-lock-open-outline": mdiLockOpenOutline,
	"mdi-lock-outline": mdiLockOutline,
	"mdi-logout": mdiLogout,
	"mdi-magnify": mdiMagnify,
	"mdi-memory": mdiMemory,
	"mdi-menu": mdiMenu,
	"mdi-menu-down": mdiMenuDown,
	"mdi-menu-right": mdiMenuRight,
	"mdi-minus": mdiMinus,
	"mdi-minus-box": mdiMinusBox,
	"mdi-monitor": mdiMonitor,
	"mdi-monitor-dashboard": mdiMonitorDashboard,
	"mdi-monitor-eye": mdiMonitorEye,
	"mdi-moon-waning-crescent": mdiMoonWaningCrescent,
	"mdi-network-pos": mdiNetworkPos,
	"mdi-numeric": mdiNumeric,
	"mdi-open-in-new": mdiOpenInNew,
	"mdi-package-variant": mdiPackageVariant,
	"mdi-package-variant-closed": mdiPackageVariantClosed,
	"mdi-page-first": mdiPageFirst,
	"mdi-page-last": mdiPageLast,
	"mdi-palette": mdiPalette,
	"mdi-paperclip": mdiPaperclip,
	"mdi-pause": mdiPause,
	"mdi-pencil": mdiPencil,
	"mdi-pencil-outline": mdiPencilOutline,
	"mdi-percent": mdiPercent,
	"mdi-play": mdiPlay,
	"mdi-plus": mdiPlus,
	"mdi-point-of-sale": mdiPointOfSale,
	"mdi-printer": mdiPrinter,
	"mdi-printer-check": mdiPrinterCheck,
	"mdi-printer-outline": mdiPrinterOutline,
	"mdi-printer-pos": mdiPrinterPos,
	"mdi-printer-settings": mdiPrinterSettings,
	"mdi-printer-wireless": mdiPrinterWireless,
	"mdi-progress-clock": mdiProgressClock,
	"mdi-radiobox-blank": mdiRadioboxBlank,
	"mdi-radiobox-marked": mdiRadioboxMarked,
	"mdi-receipt-text-clock-outline": mdiReceiptTextClockOutline,
	"mdi-receipt-text-outline": mdiReceiptTextOutline,
	"mdi-refresh": mdiRefresh,
	"mdi-refresh-circle": mdiRefreshCircle,
	"mdi-reload": mdiReload,
	"mdi-safe": mdiSafe,
	"mdi-scale-balance": mdiScaleBalance,
	"mdi-server": mdiServer,
	"mdi-source-branch": mdiSourceBranch,
	"mdi-source-commit": mdiSourceCommit,
	"mdi-star": mdiStar,
	"mdi-star-half-full": mdiStarHalfFull,
	"mdi-star-outline": mdiStarOutline,
	"mdi-store-clock-outline": mdiStoreClockOutline,
	"mdi-storefront-outline": mdiStorefrontOutline,
	"mdi-sync": mdiSync,
	"mdi-table": mdiTable,
	"mdi-tag-minus": mdiTagMinus,
	"mdi-tag-outline": mdiTagOutline,
	"mdi-text-box-check-outline": mdiTextBoxCheckOutline,
	"mdi-text-box-outline": mdiTextBoxOutline,
	"mdi-theme-light-dark": mdiThemeLightDark,
	"mdi-ticket-percent-outline": mdiTicketPercentOutline,
	"mdi-timer-outline": mdiTimerOutline,
	"mdi-timer-sand": mdiTimerSand,
	"mdi-translate": mdiTranslate,
	"mdi-tray-full": mdiTrayFull,
	"mdi-truck-delivery-outline": mdiTruckDeliveryOutline,
	"mdi-tune": mdiTune,
	"mdi-tune-vertical": mdiTuneVertical,
	"mdi-undo": mdiUndo,
	"mdi-undo-variant": mdiUndoVariant,
	"mdi-unfold-more-horizontal": mdiUnfoldMoreHorizontal,
	"mdi-update": mdiUpdate,
	"mdi-view-dashboard-outline": mdiViewDashboardOutline,
	"mdi-view-grid-outline": mdiViewGridOutline,
	"mdi-volume-high": mdiVolumeHigh,
	"mdi-volume-low": mdiVolumeLow,
	"mdi-volume-medium": mdiVolumeMedium,
	"mdi-volume-variant-off": mdiVolumeVariantOff,
	"mdi-wallet-giftcard": mdiWalletGiftcard,
	"mdi-warehouse": mdiWarehouse,
	"mdi-weight": mdiWeight,
	"mdi-weight-pound": mdiWeightPound,
	"mdi-white-balance-sunny": mdiWhiteBalanceSunny,
	"mdi-wifi": mdiWifi,
	"mdi-wifi-off": mdiWifiOff,
	"mdi-wifi-strength-alert-outline": mdiWifiStrengthAlertOutline,
	"mdi-wifi-sync": mdiWifiSync,
	"mdi-wrench-check-outline": mdiWrenchCheckOutline,
	"mdi-wrench-outline": mdiWrenchOutline,
};

export default mdiIconPaths;
